# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f901a5c2d9c3725a1788599eaf0cc0986db57a0d3372f0438c4e9379e95f154cc13587ba4114284904c00f23d978a41e3eeeabbeaae66e38db40af056ce9abec

test:
  secret_key_base: dc9ebbf6218bd0373e7224ae321b55c0f5e72b7fde6916ff209a71a00384a6ca784e92d0a3ee2503b6da14d4ddfa4ab7b60268cbc4e32a2c6e4d6cf6a9b1b729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: cc910742ceb617a024f52a90964669dcaab475d72cff1a78b74c6887f0118ecb54d3a3fffdeb0cad9f07f8afb164ab990cb383c64a390a794ae97a46bbcfc5da
